config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'caffes#home'
  get '/home',to: 'caffes#home'
#  get '/about' ,to: '#'
#  get '/service', to: '#'
#  get '/blog', to: '#'
#  get '/contacts', to: '#'
  resources :users do
    get :signup, on: :collection
    put :edit, on: :member
  end
  resources :sessions do
    get :login
    post :login, on: :collection
    delete :logout, on: :member
  end
  resources :carts do
    get :show, on: :member
  end
  resources :cart_items
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :orders do
    get :index
  end
  namespace :admin do
    resources :products do
      put :edit, on: :member
    end
    resources :users do
    get :index, on: :collection
    delete :destroy, on: :member
    end
    resources :orders do
      get :index, on: :collection
    end
  end
end

app/views/layouts/_add_product_form.haml
= form_with(model: @product, url: admin_products_url ,local:true) do |f|
  = f.label :title
  = f.text_field :title, class: 'form-control'
  = f.label :category
  = f.text_field :category, class: 'form-control'
  = f.label :price
  = f.text_field :price, class: 'form-control'
  = f.label :image
  = f.file_field :image
  %br/
  = f.submit yield(:button_text), class: 'btn btn-primary signup-bttn edit-bttn'

app/views/layouts/_dishes.haml
- Product.all.in_groups_of(4).each do |dishes|
  .items
    - dishes.each do |dish|
      - unless dish.nil?
        .item
          .picture
            = image_tag(url_for(dish.image))
          %b
            %p.title= dish.title
            %p.category= dish.category
            %p.price= number_to_currency(dish.price)
            - if logged_in? && !@current_user.admin?
              = button_to 'Add to cart',cart_items_path(product_id: dish.id) ,class: 'button carts-button is-warning add-to-carts'
            - elsif logged_in? && @current_user.admin?
              = button_to 'Add to cart',cart_items_path(product_id: dish.id) ,class: 'button carts-button is-warning add-to-carts'
              = button_to 'Delete product', admin_product_url(id: dish.id), method: :delete, class: 'button carts-button is-warning add-to-cart'
              = button_to 'Edit product', edit_admin_product_url(id: dish.id), method: :get, class: 'button carts-button is-warning add-to-cart'
            - else
              = button_to 'Add to cart', new_user_url , method: :get ,class: 'button carts-button is-warning add-to-carts'

app/views/layouts/_form.haml
= form_with(model: @user,local: true) do |f|
  = render 'shared/error_message'
  = f.label :name
  = f.text_field :name, class: 'form-control'
  = f.label :email
  = f.email_field :email, class: 'form-control'
  = f.label :password
  = f.password_field :password, class: 'form-control'
  = f.label :password_confirmation
  = f.password_field :password_confirmation, class:'form-control'
  %br/
  = f.submit yield(:button_text), class: 'btn btn-primary signup-bttn edit-bttn'

app/views/layouts/_header.haml
%div.top-container
  = render 'layouts/navbar'
  = render 'layouts/title'

app/views/layouts/_menu_bar.haml
%div
  %nav.drop-down-menu
    %ul.parent
      %li{onclick: "dropDown(this)"}
        CATEGORY
        %i.arrow.down
        %ul.child
          %li Item1
          %br/
          %li Item2
          %br/
          %li Item3
          %br/
          %li Item4
          %br/
          %li Item5
          %br/
      %li{onclick: "dropDown(this)"}
        SORTING
        %i.arrow.down
        %ul.child
          %li Item1
          %br/
          %li Item2
          %br/
          %li Item3
          %br/
          %li Item4
          %br/
          %li Item5
          %br/
      %li{onclick: "dropDown(this)"}
        VEGETARIAN
        %i.arrow.down
        %ul.child
          %li Item1
          %br/
          %li Item2
          %br/
          %li Item3
          %br/
          %li Item4
          %br/
          %li Item5
          %br/
      - if logged_in? && @current_user.admin?
        %li{onclick: "dropDown(this)"}
          ADMIN ACTIONS
          %ul.child
            %li= link_to "ADD PRODUCT", new_admin_product_url
            %br/
            %li= link_to "SEE USERS", admin_users_path
            %br/
            %li= link_to "SEE ORDERS", admin_orders_path
        %i.arrow.down
    %div.slider
      %p PRICE
      %p#first.price
      %div#my-slider
      %p#second.price

app/views/layouts/_navbar.haml
%nav
  = image_tag('caffeLogo.jpg', alt: 'Eureka Caffe Logo')
  %div.caffe-logo
    %p.logo-text EUREKA
    %P.logo-text CAFFE
  %div.right-side-info
    %b
      %p= link_to "HOME", '/home'
      %span.dot
      %p= link_to "ABOUT", '#'
      %span.dot
      %p= link_to "SERVICE", '#'
      %span.dot
      %p= link_to "BLOG", '#'
      %span.dot
      %p= link_to "CONTACTS", '#'
      %span.dot
      - if logged_in?
        %p= link_to "PROFILE", @current_user
        %span.dot
        %span.icon.is_small
          = link_to("<i class='fa fa-shopping-cart'></i>".html_safe,@current_user.cart)
        %span.dot
        %p= link_to "LOG OUT", logout_session_path(@current_user), method: :delete
      - else
        %p= link_to "SIGN UP", new_user_url
        %span.dot
        %p= link_to "LOG IN", new_session_url

app/views/layouts/_order_form.html.haml
= form_with(model: @order,url: orders_url ,local:true) do |f|
  = f.label :address
  = f.text_field :address, class: 'form-control'
  = f.label :phone_number
  = f.text_field :phone_number, class: 'form-control'
  %br/
  = f.submit yield(:button_text), class: 'btn btn-primary signup-bttn edit-bttn'

app/views/layouts/_product_form.haml
= form_with(model: @product,url: admin_product_url(@product) ,local:true) do |f|
  = f.label :title
  = f.text_field :title, class: 'form-control'
  = f.label :category
  = f.text_field :category, class: 'form-control'
  = f.label :price
  = f.text_field :price, class: 'form-control'
  = f.label :image
  = f.file_field :image
  %br/
  = f.submit yield(:button_text), class: 'btn btn-primary signup-bttn edit-bttn'

app/views/layouts/_static_dishes.haml
%div.items
  %div#left-top.item
    %div.picture
      = image_tag('f1.png',alt: 'Eggs')
    %b
      %p.title Eggs
      %p.category Breakfast
      %p.price $12
  %div#top.item
    %div.picture
      = image_tag('f2.png',alt: 'Sweets')
    %b
      %p.title Sweets
      %p.category Breakfast
      %p.price $17
  %div#top.item
    %div.picture
      = image_tag('f3.png',alt: 'Cereals')
    %b
      %p.title Gourmet Breakfast
      %p.category Breakfast
      %p.price $20
  %div#top-right.item
    %div.picture
      = image_tag('f4.png',alt: 'Risotto')
    %b
      %p.title Risotto
      %p.category Second Courses
      %p.price $45
%div.items
  %div#left.item
    %div.picture
      = image_tag('f5.png',alt: 'Meat')
    %b
      %p.title Fancy Meat
      %p.category Second Courses
      %p.price $70
  %div.item
    %div.picture
      = image_tag('f6.png',alt: 'Sea Weed Rice')
    %b
      %p.title Sea Weed Rice
      %p.category Entrees
      %p.price $37
  %div.item
    %div.picture
      = image_tag('f7.png',alt: 'Cereals')
    %b
      %p.title Spaghetti
      %p.category Second Courses
      %p.price $40
  %div#right.item
    %div.picture
      = image_tag('f8.png',alt: 'Risotto')
    %b
      %p.title Spotted Burger
      %p.category Burgers
      %p.price $70
%div.items
  %div#left.item
    %div.picture
      = image_tag('f1.png',alt: 'Eggs')
    %b
      %p.title Eggs
      %p.category Breakfast
      %p.price $12
  %div.item
    %div.picture
      = image_tag('f2.png',alt: 'Sweets')
    %b
      %p.title Sweets
      %p.category Breakfast
      %p.price $17
  %div.item
    %div.picture
      = image_tag('f3.png',alt: 'Cereals')
    %b
      %p.title Gourmet Breakfast
      %p.category Breakfast
      %p.price $20
  %div#right.item
    %div.picture
      = image_tag('f4.png',alt: 'Risotto')
    %b
      %p.title Risotto
      %p.category Second Courses
      %p.price $45
%div.items
  %div#left-bottom.item
    %div.picture
      = image_tag('f5.png',alt: 'Meat')
    %b
      %p.title Fancy Meat
      %p.category Second Courses
      %p.price $70
  %div.item
    %div#bottom.picture
      = image_tag('f6.png',alt: 'Sea Weed Rice')
    %b
      %p.title Sea Weed Rice
      %p.category Entrees
      %p.price $37
  %div#bottom.item
    %div.picture
      = image_tag('f7.png',alt: 'Cereals')
    %b
      %p.title Spaghetti
      %p.category Second Courses
      %p.price $40
  %div#bottom-right.item
    %div.picture
      = image_tag('f8.png',alt: 'Risotto')
    %b
      %p.title Spotted Burger
      %p.category Burgers
      %p.price $70

app/views/layouts/_title.haml
%h1 Ordering food
%div.fork-knife
  %p#wavy-line1 kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
  = image_tag('forkIcon.png', alt: 'Fork and knife icon.')
  %p#wavy-line2 kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
%p.description-text
  Maecenas vells at magna sagittis venenatis. Integer pretium auctor
  %br/
  magna, egestas justo gravida vitae. In lacinia auctor auctor.

app/views/layouts/application.haml
%html
%head
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%link{href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}/
%title= full_title(yield(:title))
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
%body
  - flash.each do |message_type, message|
    = content_tag(:div,message,class: "alert alert-#{message_type}")
= render 'layouts/header'
= yield